[{
    "companyName": "北京转转精神科技有限责任公司",
    "shortName": "转转",
    "time": "2018-03-26 10:16:43",
    "salary": "25k-50k",
    "companySize": "500-2000人",
    "education": "本科",
    "formatCreateTime": "10:16发布",
    "positionName": "资深web前端开发工程师",
    "stationname": null,
    "district": "朝阳区"
},{
    "companyName": "北京鼎力创世科技有限公司",
    "shortName": "51信用卡管家（北京）",
    "time": "2018-03-26 10:08:44",
    "salary": "35k-50k",
    "companySize": "500-2000人",
    "education": "本科",
    "formatCreateTime": "10:08发布",
    "positionName": "web前端",
    "stationname": "望京南",
    "district": "朝阳区"
}, {
    "companyName": "北京白山耘科技有限公司",
    "shortName": "白山云科技",
    "time": "2018-03-26 10:00:16",
    "salary": "25k-45k",
    "companySize": "150-500人",
    "education": "本科",
    "formatCreateTime": "10:00发布",
    "positionName": "Web开发工程师",
    "stationname": null,
    "district": "朝阳区"
}, {
    "companyName": "支付宝(杭州)信息技术有限公司",
    "shortName": "蚂蚁金服集团",
    "time": "2018-03-25 23:36:57",
    "salary": "25k-50k",
    "companySize": "2000人以上",
    "education": "本科",
    "formatCreateTime": "1天前发布",
    "positionName": "Web前端开发工程师-智能云平台-P7-阿里云",
    "stationname": "望京东",
    "district": "朝阳区"
}, {
    "companyName": "支付宝(杭州)信息技术有限公司",
    "shortName": "蚂蚁金服集团",
    "time": "2018-03-25 23:36:50",
    "salary": "25k-50k",
    "companySize": "2000人以上",
    "education": "本科",
    "formatCreateTime": "1天前发布",
    "positionName": "Web前端专家-智能云平台-阿里云-杭州/北京",
    "stationname": "望京南",
    "district": "朝阳区"
}, {
    "companyName": "北京三快在线科技有限公司",
    "shortName": "美团点评",
    "time": "2018-03-25 18:41:40",
    "salary": "28k-50k",
    "companySize": "2000人以上",
    "education": "本科",
    "formatCreateTime": "1天前发布",
    "positionName": "web前端架构工程师",
    "stationname": "北土城",
    "district": "朝阳区"
}, {
    "companyName": "北京嘟嘟一下科技有限公司",
    "shortName": "小打卡",
    "time": "2018-03-24 15:08:02",
    "salary": "40k-70k",
    "companySize": "15-50人",
    "education": "本科",
    "formatCreateTime": "2天前发布",
    "positionName": "Web 前端开发工程师",
    "stationname": "阜通",
    "district": "朝阳区"
}, {
    "companyName": "中本聪明(北京)科技有限公司",
    "shortName": "币印",
    "time": "2018-03-23 19:00:34",
    "salary": "30k-40k",
    "companySize": "15-50人",
    "education": "本科",
    "formatCreateTime": "3天前发布",
    "positionName": "高级web前端工程师（区块链）",
    "stationname": "望京南",
    "district": "朝阳区"
}, {
    "companyName": "飞维美地信息技术（北京）有限公司",
    "shortName": "FreeWheel",
    "time": "2018-03-23 16:44:46",
    "salary": "35k-44k",
    "companySize": "500-2000人",
    "education": "本科",
    "formatCreateTime": "3天前发布",
    "positionName": "Lead Java Web开发",
    "stationname": "枣营",
    "district": "朝阳区"
}, {
    "companyName": "飞维美地信息技术（北京）有限公司",
    "shortName": "FreeWheel",
    "time": "2018-03-23 16:44:46",
    "salary": "25k-33k",
    "companySize": "500-2000人",
    "education": "本科",
    "formatCreateTime": "3天前发布",
    "positionName": "资深Java web/Ruby开发",
    "stationname": "枣营",
    "district": "朝阳区"
}, {
    "companyName": "北京粉笔蓝天科技有限公司",
    "shortName": "粉笔网",
    "time": "2018-03-23 11:14:30",
    "salary": "30k-60k",
    "companySize": "150-500人",
    "education": "硕士",
    "formatCreateTime": "3天前发布",
    "positionName": "高级 Web 前端开发工程师",
    "stationname": "团结湖",
    "district": "朝阳区"
}, {
    "companyName": "北京动因体育科技有限公司",
    "shortName": "动因体育",
    "time": "2018-03-22 19:15:34",
    "salary": "30k-40k",
    "companySize": "2000人以上",
    "education": "本科",
    "formatCreateTime": "2018-03-22",
    "positionName": "web前端开发工程师（高级）",
    "stationname": "望京南",
    "district": "朝阳区"
}, {
    "companyName": "北京京东世纪贸易有限公司",
    "shortName": "京东集团",
    "time": "2018-03-22 18:16:01",
    "salary": "25k-50k",
    "companySize": "2000人以上",
    "education": "本科",
    "formatCreateTime": "2018-03-22",
    "positionName": "Web前端开发工程师",
    "stationname": "奥林匹克公园",
    "district": "朝阳区"
}, {
    "companyName": "北京三快在线科技有限公司",
    "shortName": "美团点评",
    "time": "2018-03-22 11:01:05",
    "salary": "25k-45k",
    "companySize": "2000人以上",
    "education": "本科",
    "formatCreateTime": "2018-03-22",
    "positionName": "高级Web前端工程师/专家",
    "stationname": "望京东",
    "district": "朝阳区"
}, {
    "companyName": "普奥云信息科技（北京）有限公司",
    "shortName": "普奥云信息",
    "time": "2018-03-22 10:44:52",
    "salary": "25k-40k",
    "companySize": "50-150人",
    "education": "本科",
    "formatCreateTime": "2018-03-22",
    "positionName": "web前端开发工程师",
    "stationname": "望京东",
    "district": "朝阳区"
}, {
    "companyName": "普奥云信息科技（北京）有限公司",
    "shortName": "普奥云信息",
    "time": "2018-03-22 10:44:52",
    "salary": "30k-40k",
    "companySize": "50-150人",
    "education": "本科",
    "formatCreateTime": "2018-03-22",
    "positionName": "web前端",
    "stationname": "望京东",
    "district": "朝阳区"
}, {
    "companyName": "阿里健康科技（中国）有限公司",
    "shortName": "阿里健康",
    "time": "2018-03-21 20:11:31",
    "salary": "25k-35k",
    "companySize": "150-500人",
    "education": "本科",
    "formatCreateTime": "2018-03-21",
    "positionName": "Web前端开发高级专家",
    "stationname": "望京东",
    "district": "朝阳区"
}, {
    "companyName": "北京永洪商智科技有限公司",
    "shortName": "永洪科技",
    "time": "2018-03-21 18:56:55",
    "salary": "25k-30k",
    "companySize": "150-500人",
    "education": "本科",
    "formatCreateTime": "2018-03-21",
    "positionName": "高级web前端工程师",
    "stationname": "国贸",
    "district": "朝阳区"
}, {
    "companyName": "北京领结科技有限公司",
    "shortName": "领结管家",
    "time": "2018-03-21 12:46:29",
    "salary": "35k-70k",
    "companySize": "50-150人",
    "education": "本科",
    "formatCreateTime": "2018-03-21",
    "positionName": "高级web前端研发工程师",
    "stationname": null,
    "district": "朝阳区"
}, {
    "companyName": "奇妙星空（北京）科技有限公司",
    "shortName": "TOPGAME",
    "time": "2018-03-21 11:37:24",
    "salary": "25k-50k",
    "companySize": "150-500人",
    "education": "本科",
    "formatCreateTime": "2018-03-21",
    "positionName": "web前端负责人",
    "stationname": null,
    "district": "朝阳区"
}, {
    "companyName": "北京汇众嘉悦信息咨询有限公司",
    "shortName": "PartnerUnite",
    "time": "2018-03-20 17:30:30",
    "salary": "30k-50k",
    "companySize": "少于15人",
    "education": "本科",
    "formatCreateTime": "2018-03-20",
    "positionName": "web前端开发工程师",
    "stationname": null,
    "district": "朝阳区"
}, {
    "companyName": "中信百信银行股份有限公司",
    "shortName": "百信银行",
    "time": "2018-03-20 08:59:09",
    "salary": "25k-50k",
    "companySize": "150-500人",
    "education": "硕士",
    "formatCreateTime": "2018-03-20",
    "positionName": "web前端高级开发",
    "stationname": "东直门",
    "district": "朝阳区"
}, {
    "companyName": "奇虎360科技有限公司",
    "shortName": "360",
    "time": "2018-03-19 11:17:24",
    "salary": "25k-35k",
    "companySize": "2000人以上",
    "education": "本科",
    "formatCreateTime": "2018-03-19",
    "positionName": "web服务端测试开发",
    "stationname": "望京南",
    "district": "朝阳区"
}, {
    "companyName": "趣分期（北京）信息技术有限公司",
    "shortName": "趣店",
    "time": "2018-03-19 10:11:20",
    "salary": "30k-40k",
    "companySize": "500-2000人",
    "education": "本科",
    "formatCreateTime": "2018-03-19",
    "positionName": "Web前端高级工程师",
    "stationname": "奥林匹克公园",
    "district": "朝阳区"
}, {
    "companyName": "北京分享动力网络科技有限公司",
    "shortName": "分享动力",
    "time": "2018-03-16 15:41:01",
    "salary": "30K-50K",
    "companySize": "15-50人",
    "education": "本科",
    "formatCreateTime": "2018-03-16",
    "positionName": "高级web前端开发工程师（leader）",
    "stationname": "东四",
    "district": "朝阳区"
}, {
    "companyName": "北京闪银奇异科技有限公司",
    "shortName": "闪银奇异",
    "time": "2018-03-15 16:56:56",
    "salary": "25k-40k",
    "companySize": "500-2000人",
    "education": "本科",
    "formatCreateTime": "2018-03-15",
    "positionName": "资深web前端开发工程师",
    "stationname": "枣营",
    "district": "朝阳区"
}, {
    "companyName": "北京三快在线科技有限公司",
    "shortName": "美团点评",
    "time": "2018-03-15 20:45:56",
    "salary": "30k-60k",
    "companySize": "2000人以上",
    "education": "本科",
    "formatCreateTime": "2018-03-15",
    "positionName": "web高级前端工程师-平台业务",
    "stationname": "望京东",
    "district": "朝阳区"
}, {
    "companyName": "趣分期（北京）信息技术有限公司",
    "shortName": "趣店",
    "time": "2018-03-14 15:48:34",
    "salary": "30k-40k",
    "companySize": "500-2000人",
    "education": "本科",
    "formatCreateTime": "2018-03-14",
    "positionName": "高级Web前端工程师",
    "stationname": "奥林匹克公园",
    "district": "朝阳区"
}, {
    "companyName": "趣分期（北京）信息技术有限公司",
    "shortName": "趣店",
    "time": "2018-03-14 15:17:26",
    "salary": "30k-40k",
    "companySize": "500-2000人",
    "education": "本科",
    "formatCreateTime": "2018-03-14",
    "positionName": "高级Web前端工程师",
    "stationname": "奥林匹克公园",
    "district": "朝阳区"
}, {
    "companyName": "杰仕联科管理咨询（北京）有限公司",
    "shortName": "杰仕联科",
    "time": "2018-03-12 11:47:34",
    "salary": "25K-35K",
    "companySize": "150-500人",
    "education": "本科",
    "formatCreateTime": "2018-03-12",
    "positionName": "Web前端开发工程师",
    "stationname": null,
    "district": "朝阳区"
}, {
    "companyName": "上海谦问万答吧云计算科技有限公司",
    "shortName": "学霸君",
    "time": "2018-03-12 09:45:57",
    "salary": "25k-35k",
    "companySize": "150-500人",
    "education": "本科",
    "formatCreateTime": "2018-03-12",
    "positionName": "高级web前端开发工程师",
    "stationname": "望京东",
    "district": "朝阳区"
}, {
    "companyName": "北京毫末科技有限公司",
    "shortName": "毫末科技",
    "time": "2018-03-10 14:29:50",
    "salary": "30k-45k",
    "companySize": "50-150人",
    "education": "本科",
    "formatCreateTime": "2018-03-10",
    "positionName": "高级Web开发工程师",
    "stationname": "海淀黄庄",
    "district": "朝阳区"
}, {
    "companyName": "趣分期（北京）信息技术有限公司",
    "shortName": "趣店",
    "time": "2018-03-10 11:29:21",
    "salary": "30k-40k",
    "companySize": "500-2000人",
    "education": "本科",
    "formatCreateTime": "2018-03-10",
    "positionName": "Web前端高级工程师",
    "stationname": "奥林匹克公园",
    "district": "朝阳区"
}, {
    "companyName": "盛世瑞泰",
    "shortName": "盛世瑞泰",
    "time": "2018-03-08 10:53:31",
    "salary": "25k-35k",
    "companySize": "15-50人",
    "education": "本科",
    "formatCreateTime": "2018-03-08",
    "positionName": "高级WEB开发工程师",
    "stationname": "枣营",
    "district": "朝阳区"
}, {
    "companyName": "北京很嗨森科技有限公司",
    "shortName": "KK点歌",
    "time": "2018-03-07 20:42:24",
    "salary": "25k-35k",
    "companySize": "少于15人",
    "education": "本科",
    "formatCreateTime": "2018-03-07",
    "positionName": "高级Web前端开发",
    "stationname": "望京南",
    "district": "朝阳区"
}, {
    "companyName": "北京多又科技有限公司",
    "shortName": "多又科技",
    "time": "2018-03-06 10:09:16",
    "salary": "25k-50k",
    "companySize": "15-50人",
    "education": "本科",
    "formatCreateTime": "2018-03-06",
    "positionName": "Web前端高级工程师",
    "stationname": "金台路",
    "district": "朝阳区"
}, {
    "companyName": "北京新橙科技有限公司",
    "shortName": "iCourt",
    "time": "2018-03-05 20:07:54",
    "salary": "25k-35k",
    "companySize": "150-500人",
    "education": "本科",
    "formatCreateTime": "2018-03-05",
    "positionName": "中高级web前端工程师",
    "stationname": "四惠东",
    "district": "朝阳区"
}]